name: Dependency Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dependency-review:
    name: Dependency review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Dependency Review Action
        uses: github/dependency-review-action@v4
      - name: Run cargo-audit
        uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
